version: '2'
services:

  portainer:
    labels:
      - "docker.group=IOTstack"
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/sda/docker/volumes/portainer/data:/data

  influxdb:
    labels:
        - "docker.group=IOTstack"
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - /mnt/sda/docker/volumes/influxdb/data:/var/lib/influxdb
      - /mnt/sda/docker/backups/influxdb/db:/var/lib/influxdb/backup

  grafana:
    labels:
      - "docker.group=IOTstack"
    container_name: grafana
    image: grafana/grafana:6.3.6
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - /mnt/sda/docker/volumes/grafana/data:/var/lib/grafana
      - /mnt/sda/docker/volumes/grafana/log:/var/log/grafana

  pihole:
    labels:
      - "docker.group=IOTstack"
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8089:80/tcp"
      #- "443:443/tcp"
    env_file:
      - ./services/pihole/pihole.env
    volumes:
       - /mnt/sda/docker/volumes/pihole/etc-pihole/:/etc/pihole/
       - /mnt/sda/docker/volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  plex:
    labels:
      - "docker.group=IOTstack"
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
    volumes:
      - /mnt/sda/docker/volumes/plex/config:/config
      #- ~/mnt/HDD/tvseries:/tv
      #- ~/mnt/HDD/movies:/movies
      - /mnt/sda/docker/volumes/plex/transcode:/transcode
    restart: unless-stopped

  qbittorrent:
    labels:
      - "docker.group=IOTstack"
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - WEBUI_PORT=15080
    volumes:
      - /mnt/sda/docker/volumes/qbittorrent/config:/config
      - /mnt/sda/docker/volumes/qbittorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 15080:15080
      - 1080:1080

  # DEPCRECADO A FAVOR DE FILEBROWSER
  # cdn:
  #   image: agustinlare/cdn
  #   container_name: cdn
  #   environment:
  #     - SERVE_PATH=/public
  #     - SERVER_PREFIX=/
  #   volumes:
  #     - /mnt/sda:/public
  #   ports:
  #     - 80:80

  filebrowser:
    labels:
      - "docker.group=IOTstack"
    image: filebrowser/filebrowser:pi
    container_name: filebrowser
    volumes:
      - /mnt/sda:/srv
      - /mnt/sda/docker/volumes/filebrowser/database.db:/database.db
      - /mnt/sda/docker/volumes/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 80:80